Repository deathlesz/habit-tracker, pull requests merged in 2025-08, with the labels that each got.

#6 Create feature set document and describe product features
  docs/feature-set.md
Labels: documentation

#34 Create edit page UI design
  docs/UI/edit_page_UI.png
Labels: frontend

#40 Fix build issues
  src/Presentation/HabitTracker.Presentation/HabitTracker.Presentation.csproj
Labels: backend

#67 Update tech stack and create Overview in README.md
  README.md
Labels: documentation

#75 Fix caching of MAUI workloads in CI
  .github/workflows/build_and_test.yml
Labels: automation
